name: Deploy to Droplet

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Run remote commands with sshpass
        run: |
          sshpass -p "${{ secrets.PASSPHRASE }}" ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << EOF
            docker pull ubuntu:latest
            docker run -d --name ci-ubuntu ubuntu:latest sleep infinity
          EOF
